package com.narutoai.chat.data

import android.content.Context
import androidx.room.*
import kotlinx.coroutines.flow.Flow

/**
 * Entité Room pour les personnages personnalisés
 */
@Entity(tableName = "custom_characters")
data class CustomCharacterEntity(
    @PrimaryKey
    val id: String,
    val name: String,
    val description: String,
    val systemPromptSFW: String,
    val systemPromptNSFW: String,
    val avatarImagePath: String = "", // Chemin vers l'image locale
    val personality: String = "", // JSON array
    
    // Détails physiques
    val physicalDescription: String = "",
    val age: String = "",
    val height: String = "",
    val hairColor: String = "",
    val eyeColor: String = "",
    val bodyType: String = "",
    val distinctiveFeatures: String = "", // JSON array
    
    // Background
    val scenario: String = "",
    val backgroundStory: String = "",
    
    // Tempérament
    val temperament: String = "",
    val characterTraits: String = "", // JSON array
    val likes: String = "", // JSON array
    val dislikes: String = "", // JSON array
    val skills: String = "", // JSON array
    
    // Greeting
    val greetingMessage: String = "",
    
    // Métadonnées
    val createdAt: Long = System.currentTimeMillis(),
    val isAutoGenerated: Boolean = false // Si généré depuis photo
)

/**
 * DAO pour les personnages personnalisés
 */
@Dao
interface CustomCharacterDao {
    
    @Query("SELECT * FROM custom_characters ORDER BY createdAt DESC")
    fun getAllCharacters(): Flow<List<CustomCharacterEntity>>
    
    @Query("SELECT * FROM custom_characters WHERE id = :id")
    suspend fun getCharacterById(id: String): CustomCharacterEntity?
    
    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insertCharacter(character: CustomCharacterEntity)
    
    @Update
    suspend fun updateCharacter(character: CustomCharacterEntity)
    
    @Delete
    suspend fun deleteCharacter(character: CustomCharacterEntity)
    
    @Query("DELETE FROM custom_characters WHERE id = :id")
    suspend fun deleteCharacterById(id: String)
    
    @Query("SELECT COUNT(*) FROM custom_characters")
    suspend fun getCharacterCount(): Int
}

/**
 * Base de données Room
 */
@Database(
    entities = [CustomCharacterEntity::class],
    version = 1,
    exportSchema = false
)
abstract class CustomCharacterDatabase : RoomDatabase() {
    abstract fun customCharacterDao(): CustomCharacterDao
    
    companion object {
        @Volatile
        private var INSTANCE: CustomCharacterDatabase? = null
        
        fun getDatabase(context: Context): CustomCharacterDatabase {
            return INSTANCE ?: synchronized(this) {
                val instance = Room.databaseBuilder(
                    context.applicationContext,
                    CustomCharacterDatabase::class.java,
                    "custom_characters_database"
                )
                    .fallbackToDestructiveMigration()
                    .build()
                INSTANCE = instance
                instance
            }
        }
    }
}

/**
 * Repository pour les personnages personnalisés
 */
class CustomCharacterRepository(private val dao: CustomCharacterDao) {
    
    val allCharacters: Flow<List<CustomCharacterEntity>> = dao.getAllCharacters()
    
    suspend fun getCharacterById(id: String): CustomCharacterEntity? {
        return dao.getCharacterById(id)
    }
    
    suspend fun insertCharacter(character: CustomCharacterEntity) {
        dao.insertCharacter(character)
    }
    
    suspend fun updateCharacter(character: CustomCharacterEntity) {
        dao.updateCharacter(character)
    }
    
    suspend fun deleteCharacter(character: CustomCharacterEntity) {
        dao.deleteCharacter(character)
    }
    
    suspend fun deleteCharacterById(id: String) {
        dao.deleteCharacterById(id)
    }
    
    suspend fun getCharacterCount(): Int {
        return dao.getCharacterCount()
    }
}
